<<<<<<< HEAD
0000
=======
1111Everything up-to-date
2222
<<<<<<< HEAD
3333
>>>>>>> 20230305 10:35:01
To 244564485.github.com:244564485/jupyter.git
 ! [rejected]        main -> main (non-fast-forward)
error: failed to push some refs to 'git@244564485.github.com:244564485/jupyter.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
6. 10 40 20230305
=======
3333kex_exchange_identification: Connection closed by remote host
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
6. 10 35 20230305
>>>>>>> 20230305 10:40:02
